<%@ Page Language="C#" MasterPageFile="~/HRMS.master" CodeFile="TrainerProfile.aspx.cs" Inherits="Hrms_Training_Default" Title="Welcome to HRMS Training Module" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <style type="text/css">
        .left
        {
            margin-left: 250px;
            left: 250px;
        }
    </style>
        <style type="text/css">
    .rateStar
    {
	    white-space:nowrap;
	    margin:0em;
	    height:14px;
	    
    }
    .rateItem 
    {
        font-size: 0pt;
        width: 13px;
        height: 12px;
        margin: 0px;
        padding: 0px;
        display: block;
        
        background-repeat: no-repeat;
	    cursor:pointer;
    }
    .FillStar
    {
        background-image: url("ratingfilled.png");
    }
    .EmptyStar 
    {
        background-image: url("ratingempty.png");
    }
    .SaveStar
    {
        background-image: url(ratingsaved.png);
    }
    </style>
    
    <div><h3 class="page-header">Trainer Profile</h3></div>

    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:connectionstring %>"
                SelectCommand="SELECT id,ins_name, Type, imagedata, address1, address2, city, country, email, state, phone, website, category, grade, certifications, awards, ins_branch FROM institution_profile WHERE (id = @id)"
                UpdateCommand="update institution_profile set ins_name=@ins_name, type=@type, address1=@address1, address2=@address2, city=@city, country=@country, email=@email, state=@state, phone=@phone, website=@website, category=@category, grade=@grade, certifications=@certifications, awards=@awards, ins_branch=@ins_branch  WHERE (id = @id)">
                <SelectParameters>
                    <asp:QueryStringParameter QueryStringField="id" Name="id" Type="Int32" />                    
                    
                </SelectParameters>
                <UpdateParameters>
                    <asp:Parameter Name="ins_name" Type="String" />
                    <asp:Parameter Name="Type" Type="String" />
                    <asp:Parameter Name="address1" Type="String" />
                    <asp:Parameter Name="address2" Type="String" />
                    <asp:Parameter Name="city" Type="String" />
                    <asp:Parameter Name="country" Type="String" />
                    <asp:Parameter Name="email" Type="String" />
                    <asp:Parameter Name="state" Type="String" />
                    <asp:Parameter Name="phone" Type="Int64" />
                    <asp:Parameter Name="website" Type="String" />
                    <asp:Parameter Name="Category" Type="String" />
                    <asp:Parameter Name="Grade" Type="String" />
                    <asp:Parameter Name="Certifications" Type="String" />
                    <asp:Parameter Name="Awards" Type="String" />
                    <asp:Parameter Name="Ins_Branch" Type="String" />
                    <asp:Parameter Name="id" />
                </UpdateParameters>
            </asp:SqlDataSource>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>
        <div style="width:50%">
                    <table cellpadding="1%" cellspacing="1%" width="100%" class="table table-striped table-bordered table-hover">
                        
                        <tr>
                            <td>
                                <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateRows="False" CssClass="table table-hover table-striped" DataKeyNames="id" DataSourceID="SqlDataSource1" >
                                   
                                    <HeaderTemplate>
                                     
                                        <asp:Image ImageAlign="Middle" ID="imglogo" runat="server" Height="121px" ImageUrl='<%#"Handler.ashx?id=" + Eval("id") %>' Width="107px" />
                                    </HeaderTemplate>
                                    <Fields>
                                        <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" Visible="false" />
                                        <asp:BoundField DataField="ins_name" HeaderText="Institute Name" SortExpression="ins_name" />
                                        <asp:BoundField DataField="Type" HeaderText="Type" SortExpression="Type" />
                                        <asp:BoundField DataField="address1" HeaderText="Address1" SortExpression="address1" />
                                        <asp:BoundField DataField="address2" HeaderText="Address2" SortExpression="address2" />
                                        <asp:BoundField DataField="city" HeaderText="City" SortExpression="city" />
                                        <asp:BoundField DataField="country" HeaderText="Country" SortExpression="country" />
                                        <asp:BoundField DataField="email" HeaderText="Email-ID" SortExpression="email" />
                                        <asp:BoundField DataField="state" HeaderText="State" SortExpression="state" />
                                        <asp:BoundField ControlStyle-Width="155px" DataField="phone" HeaderText="Phone" SortExpression="phone">
                                        <ControlStyle Width="155px" />
                                        </asp:BoundField>
                                        <asp:BoundField DataField="website" HeaderText="WebSite" SortExpression="website" />
                                        <asp:BoundField DataField="Category" HeaderText="Category" SortExpression="Category" />
                                        <asp:BoundField DataField="Grade" HeaderText="Grade" SortExpression="Grade" />
                                        <asp:BoundField DataField="Certifications" HeaderText="Certifications" SortExpression="Certifications" />
                                        <asp:BoundField DataField="Awards" HeaderText="Awards" SortExpression="Awards" />
                                        <asp:BoundField DataField="Ins_branch" HeaderText="Branches" SortExpression="ins_branch" />
                                    </Fields>
                                    <EditRowStyle BackColor="White" />
                                </asp:DetailsView>
                            </td>
                        </tr>
                     </table>   
                     </div>
                     <div>  

                           <asp:ListView ID="lv_trainers" runat="server" OnItemCanceling="lv_trainers_ItemCanceling" OnItemEditing="lv_trainers_ItemEditing" OnItemUpdating="lv_trainers_ItemUpdating">
                               <LayoutTemplate>
                                   <table align="center" border="1" class="table table-hover table-striped">
                                       <tr color:="" white"="">
                                           <th>
                                               <asp:Label ID="lblTName" runat="server" Text="TrainerName"></asp:Label>
                                           </th>
                                           <th>
                                               <asp:Label ID="lblptype" runat="server" Text="ptype"></asp:Label>
                                           </th>
                                           <th>
                                               <asp:Label ID="lblTExperiance" runat="server" Text="Experience in hrs"></asp:Label>
                                           </th>
                                           <th>
                                               <asp:Label ID="lblTSpecification" runat="server" Text="Specification"></asp:Label>
                                           </th>
                                           <th>
                                               <asp:Label ID="lblTWorktype" runat="server" Text="WorkType"></asp:Label>
                                           </th>
                                           <th>
                                               <asp:Label ID="lblTRating" runat="server" Text="Rating"></asp:Label>
                                           </th>
                                           <th>
                                               <asp:Label ID="Label1" runat="server" Text="Edit"></asp:Label>
                                           </th>
                                       </tr>
                                       <tr id="itemPlaceHolder" runat="server">
                                       </tr>
                                   </table>
                               </LayoutTemplate>
                               <EmptyItemTemplate>
                                   <asp:Label ID="lblempty" runat="server" Text="No Data Found"></asp:Label>
                               </EmptyItemTemplate>
                               <ItemTemplate>
                                   <tr style="font-family: Calibri;">
                                       <asp:Label ID="IlblTid" runat="server" Text='<%#Eval("trainer_id") %>' Visible="false"></asp:Label>
                                       <td>
                                           <asp:Label ID="lblTName1" runat="server" Text='<%#Eval("fname") %>'></asp:Label>
                                       </td>
                                       <td>
                                           <asp:Label ID="lblptype0" runat="server" Text='<%#Eval("ptype") %>'></asp:Label>
                                       </td>
                                       <td>
                                           <asp:Label ID="lblTExperiance1" runat="server" Text='<%#Eval("experience") %>'></asp:Label>
                                       </td>
                                       <td>
                                           <asp:Label ID="lblTSpecification1" runat="server" Text='<%#Eval("specification") %>'></asp:Label>
                                       </td>
                                       <td>
                                           <asp:Label ID="lblTWorktype1" runat="server" Text='<%#Eval("worktype") %>'></asp:Label>
                                       </td>
                                       <td>
                                           <asp:Rating ID="Rating1" runat="server" CssClass="rateStar" CurrentRating='<%# String.IsNullOrEmpty(Eval("rating").ToString())?0:Eval("rating") %>' Direction="LeftToRight" EmptyStarCssClass="EmptyStar" FilledStarCssClass="FillStar" Height="10px" MaxRating="10" StarCssClass="rateItem" WaitingStarCssClass="SaveStar" Width="144px">
                                           </asp:Rating>
                                       </td>
                                       <td>
                                           <asp:Button ID="Tedit_but" runat="server" CommandName="Edit" Text="Edit" />
                                       </td>
                                   </tr>
                               </ItemTemplate>
                               <EditItemTemplate>
                                   <tr>
                                       <asp:Label ID="lblTid" runat="server" Text='<%#Eval("trainer_id") %>' Visible="false"></asp:Label>
                                       <td>
                                           <asp:TextBox ID="txtname" runat="server" MaxLength="20" Text='<%#Eval("fname") %>' Width="100px"></asp:TextBox>
                                       </td>
                                       <td>
                                           <asp:TextBox ID="txtptype" runat="server" MaxLength="20" Text='<%#Eval("ptype") %>' Width="100px"></asp:TextBox>
                                       </td>
                                       <td>
                                           <asp:TextBox ID="txtexp" runat="server" MaxLength="2" Text='<%#Eval("experience") %>' Width="100px"></asp:TextBox>
                                       </td>
                                       <td>
                                           <asp:TextBox ID="txtspe" runat="server" MaxLength="20" Text='<%#Eval("specification") %>' Width="100px"></asp:TextBox>
                                       </td>
                                       <td>
                                           <asp:TextBox ID="txtwt" runat="server" MaxLength="20" Text='<%#Eval("worktype") %>' Width="100px"></asp:TextBox>
                                       </td>
                                       <td>
                                           <asp:Rating ID="Rating2" runat="server" CssClass="rateStar" CurrentRating='<%# String.IsNullOrEmpty(Eval("rating").ToString())?0:Eval("rating") %>' Direction="LeftToRight" EmptyStarCssClass="EmptyStar" FilledStarCssClass="FillStar" Height="10px" MaxRating="10" StarCssClass="rateItem" WaitingStarCssClass="SaveStar" Width="144px">
                                           </asp:Rating>
                                       </td>
                                       <td>
                                           <asp:Button ID="Tup_but" runat="server" CommandName="Update" Text="Update" />
                                       </td>
                                       <td>
                                           <asp:Button ID="Tcan_but" runat="server" CommandName="Cancel" Text="Cancel" />
                                       </td>
                                   </tr>
                               </EditItemTemplate>
                           </asp:ListView>
                           </td>                                    
           </div>
    </ContentTemplate>
    </asp:UpdatePanel>


    
    <br />
    <%--Trainer Profile--%>
    <asp:LinkButton ID="lnkgoback" runat="server" Text="Back To Institutes" 
        PostBackUrl="~/Hrms_Master/Training/Programtype.aspx" Font-Names="Calibri"></asp:LinkButton>
</asp:Content>
